# Generated by Django 6.0.1 on 2026-02-09 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0005_localdeposit_paid_at_localdeposit_referrer'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='referrer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_profiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
